theme = "modus_vivendi_custom"

[editor]
clipboard-provider = "pasteboard"
default-yank-register = "+"
end-of-line-diagnostics = "warning"

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[editor.statusline]
right = ["diagnostics", "position", "file-type"]
