[general]
always_show_help.enabled = true
confirm_quit.enabled = false
refresh_on_file_change.enabled = true
mouse_support = false

[style]
separator = { mods = "DIM" }

info_msg = { fg = "green", mods = "BOLD" }
error_msg = { fg = "red", mods = "BOLD" }
command = { fg = "blue", mods = "BOLD" }

menu.heading = { fg = "blue", mods = "BOLD" }
menu.key = { fg = "magenta" }
menu.active_arg = { fg = "yellow", mods = "BOLD" }

prompt = { fg = "cyan", mods = "DIM" }

section_header = { fg = "yellow" }
file_header = { fg = "magenta" }
hunk_header = { fg = "blue" }

diff_highlight.tag_old = { fg = "red", mods = "BOLD" }
diff_highlight.tag_new = { fg = "green", mods = "BOLD" }
diff_highlight.unchanged_old = { mods = "DIM" }
diff_highlight.unchanged_new = { mods = "DIM" }
diff_highlight.changed_old = { fg = "red" }
diff_highlight.changed_new = { fg = "green" }

syntax_highlight.enabled = true
syntax_highlight.comment = { fg = "gray" }
syntax_highlight.function_builtin = { fg = "cyan" }
syntax_highlight.function = { fg = "blue" }
syntax_highlight.keyword = { fg = "magenta" }
syntax_highlight.module = { fg = "cyan" }
syntax_highlight.string_special = { fg = "yellow" }
syntax_highlight.string = { fg = "yellow" }
syntax_highlight.type = { fg = "yellow" }
syntax_highlight.type_builtin = { fg = "yellow" }

picker.prompt = { fg = "cyan" }
picker.info = { mods = "DIM" }
picker.selection_line = { mods = "BOLD" }
picker.matched = { fg = "yellow", mods = "BOLD" }

cursor = { symbol = "|", fg = "blue" }
selection_bar = { symbol = "|", fg = "blue", mods = "DIM" }
