gui:
  theme:
    activeBorderColor:
      - "#2fafff"
      - bold
    inactiveBorderColor:
      - "#61647a"
    searchingActiveBorderColor:
      - "#b6a0ff"
      - bold
    optionsTextColor:
      - "#2fafff"
    selectedLineBgColor:
      - "#2a2a3a"
    inactiveViewSelectedLineBgColor:
      - "#1a1a22"
    selectedRangeBgColor:
      - "#61647a"
    cherryPickedCommitBgColor:
      - "#44bc44"
    cherryPickedCommitFgColor:
      - "#1e1e1e"
    markedBaseCommitBgColor:
      - "#2a2a3a"
    markedBaseCommitFgColor:
      - "#e0e6f0"
    unstagedChangesColor:
      - "#ff5f59"
    defaultFgColor:
      - "#e0e6f0"
  authorColors:
    "*": "#b6a0ff"
